# Pre-processing and Training Data Development

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler

In [2]:
tornado = pd.read_csv('/Users/gregoryolson/Documents/Data Science CT/Capstone/Capstone_Tornado/Data/tornado_downsized.csv')

In [3]:
tornado.head()

,LATITUDE,LONGITUDE,ELEVATION,DEWP,GUST,MAX,MIN,MXSPD,PRCP,SLP,STP,TEMP,VISIB,WDSP,TORNADO,APRIL,JULY
0,30.46361,-88.53194,5.5,67.2,24.1,75.9,66.0,15.0,0.01,1014.1,13.7,70.4,3.4,11.9,0,0,0
1,32.33667,-90.22139,104.2,68.1,18.1,82.9,71.1,12.0,0.00,1017.2,5.7,75.6,8.7,7.6,0,0,0
2,30.41190,-89.08080,12.8,78.0,20.0,96.1,79.0,15.9,0.00,1011.4,10.3,84.4,7.8,2.9,0,0,0
3,33.65000,-88.45000,66.8,67.6,22.0,77.5,66.9,15.9,1.60,1016.9,8.9,70.9,9.4,5.2,0,0,0
4,34.26220,-88.77130,110.0,66.2,22.9,86.0,66.9,13.0,1.05,1014.8,2.1,73.0,8.9,5.5,0,0,0

In [4]:
# create X and y variables
cols = tornado.columns
cols = cols.drop(['TORNADO'])

X = tornado[cols]
y = tornado['TORNADO']

In [5]:
# perfom RobustScaler
transformer = RobustScaler().fit(X)
X = transformer.transform(X)
df = pd.DataFrame(X, columns=cols)
df.describe()

,LATITUDE,LONGITUDE,ELEVATION,DEWP,GUST,MAX,MIN,MXSPD,PRCP,SLP,STP,TEMP,VISIB,WDSP,APRIL,JULY
count,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000,930.000000
mean,-0.042051,-0.142805,-0.048956,-0.206073,0.262341,-0.103182,-0.144260,0.264886,1.240687,0.095323,0.114450,-0.126718,-0.383154,0.132016,0.146237,0.052688
std,0.546260,0.578313,0.585558,0.742932,0.881519,0.769082,0.645600,0.891131,3.103752,0.872399,0.684564,0.715134,0.963737,0.773467,0.353533,0.223530
min,-0.873778,-1.387695,-0.995130,-3.030151,-1.011236,-2.982456,-2.256757,-1.311475,0.000000,-2.316667,-0.888889,-2.615804,-7.083333,-1.350000,0.000000,0.000000
25%,-0.478405,-0.569727,-0.451299,-0.623116,-0.325843,-0.526316,-0.594595,-0.327869,0.000000,-0.433333,-0.430199,-0.559946,-0.666667,-0.425000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.521595,0.430273,0.548701,0.376884,0.674157,0.473684,0.405405,0.672131,1.000000,0.566667,0.569801,0.440054,0.333333,0.575000,0.000000,0.000000
max,0.875913,0.548893,0.959416,0.874372,4.606742,1.345029,0.900901,4.098361,33.057471,4.033333,2.985755,1.062670,0.333333,3.725000,1.000000,1.000000

In [6]:
# convert month columns to int
df['APRIL'] = tornado['APRIL'].astype(int)
df['JULY'] = tornado['JULY'].astype(int)
df.head()

,LATITUDE,LONGITUDE,ELEVATION,DEWP,GUST,MAX,MIN,MXSPD,PRCP,SLP,STP,TEMP,VISIB,WDSP,APRIL,JULY
0,-0.850279,0.492887,-0.995130,0.301508,0.348315,-0.181287,0.265766,0.163934,0.045977,-0.316667,0.672365,0.103542,-5.166667,1.400,0,0
1,0.000895,-0.661856,0.607143,0.346734,-0.325843,0.228070,0.495495,-0.327869,0.000000,0.200000,-0.239316,0.386921,-0.750000,0.325,0,0
2,-0.873778,0.117740,-0.876623,0.844221,-0.112360,1.000000,0.851351,0.311475,0.000000,-0.766667,0.284900,0.866485,-1.500000,-0.850,0,0
3,0.597711,0.548893,0.000000,0.321608,0.112360,-0.087719,0.306306,0.311475,7.356322,0.150000,0.125356,0.130790,-0.166667,-0.275,0,0
4,0.875913,0.329284,0.701299,0.251256,0.213483,0.409357,0.306306,-0.163934,4.827586,-0.200000,-0.649573,0.245232,-0.583333,-0.200,0,0

In [7]:
# assign new df to X
X = df

In [8]:
# split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=99)

In [9]:
df.to_csv('/Users/gregoryolson/Documents/Data Science CT/Capstone/Capstone_Tornado/Data/tornado_modeling.csv', index=False)